### ISSUE TITLE
error building on macos

### ISSUE THREAD

**Issue by vinbrule** [andreikop/enki-ng#2]
I built the source code and got this error:

---

12:24:47: Running steps for project enki...
12:24:47: Starting: "/usr/local/Cellar/cmake/3.16.3/bin/cmake" --build . --target all
[  1%] Automatic MOC and UIC for target qutepart
[  1%] Built target qutepart_autogen
[  2%] Building CXX object lib/CMakeFiles/qutepart.dir/src/qutepart.cpp.o
In file included from /Users/van/Downloads/tmp/enki-ng/lib/src/qutepart.cpp:1:
In file included from /Users/van/Qt/5.9.9/clang_64/lib/QtWidgets.framework/Headers/QAction:1:
In file included from /Users/van/Qt/5.9.9/clang_64/lib/QtWidgets.framework/Headers/qaction.h:43:
In file included from /Users/van/Qt/5.9.9/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h:43:
In file included from /Users/van/Qt/5.9.9/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h:43:
In file included from /Users/van/Qt/5.9.9/clang_64/lib/QtCore.framework/Headers/qglobal.h:109:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:644:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2339:5: error: delete called on non-final 'Qutepart::IndentAlgImpl' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
    delete __ptr;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2652:7: note: in instantiation of member function 'std::__1::default_delete<Qutepart::IndentAlgImpl>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2606:19: note: in instantiation of member function 'std::__1::unique_ptr<Qutepart::IndentAlgImpl, std::__1::default_delete<Qutepart::IndentAlgImpl> >::reset' requested here
  ~unique_ptr() { reset(); }
                  ^
/Users/van/Downloads/tmp/enki-ng/lib/src/indent/indenter.h:16:7: note: in instantiation of member function 'std::__1::unique_ptr<Qutepart::IndentAlgImpl, std::__1::default_delete<Qutepart::IndentAlgImpl> >::~unique_ptr' requested here
class Indenter: public QObject {
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2652:7: note: in instantiation of member function 'std::__1::default_delete<Qutepart::Indenter>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2606:19: note: in instantiation of member function 'std::__1::unique_ptr<Qutepart::Indenter, std::__1::default_delete<Qutepart::Indenter> >::reset' requested here
  ~unique_ptr() { reset(); }
                  ^
/Users/van/Downloads/tmp/enki-ng/lib/src/qutepart.cpp:43:15: note: in instantiation of member function 'std::__1::unique_ptr<Qutepart::Indenter, std::__1::default_delete<Qutepart::Indenter> >::~unique_ptr' requested here
    indenter_(std::make_unique<Indenter>()),
              ^
1 error generated.
make[2]: *** [lib/CMakeFiles/qutepart.dir/src/qutepart.cpp.o] Error 1
make[1]: *** [lib/CMakeFiles/qutepart.dir/all] Error 2
make: *** [all] Error 2
12:24:48: The process "/usr/local/Cellar/cmake/3.16.3/bin/cmake" exited with code 2.
Error while building/deploying project enki (kit: Desktop Qt 5.9.9 clang 64bit)
When executing step "CMake Build"
12:24:48: Elapsed time: 00:01.

----

    

`error: delete called on non-final 'Qutepart::IndentAlgImpl' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
    delete __ptr;`
However, it works perfect on Linux.

By the way, the requirement of Enki-editor is Qt 5.9. it is not compatible with newer version.

**Comment by andreikop** [comment]
@hvt2 , thanks, fixed this error. Check if you have more errors on the mac os compiler.
 What is the problem with Qt > 5.9 ?

**Comment by vinbrule** [comment]
You are so fast @andreikop. After following your description, no error on Qt >5.9 anymore
